mmanela/chutzpah

- Chutzpah/BatchCompiler/BatchCompilerService.cs
- Chutzpah/Coverage/BlanketJsCoverageEngine.cs
- Chutzpah/Models/BatchCompileConfiguration.cs
- Chutzpah/Models/ChutzpahTestSettingsFile.cs
- Facts.Integration/JS/Test/Coverage/SourceMaps/chutzpah.json
- Facts/Library/BatchCompilerServiceFacts.cs
- Facts/Library/Coverage/BlanketJsCoverageEngineFacts.cs
Per discussion on #316, moving UseSourceMaps setting to Compile section rather than having it be a top-level configuration setting.
> Moving UseSourceMaps setting to within the Compile setting

- VS2012/source.extension.vsixmanifest
The installation was failing with an error "The extension 'Chutzpah Test Adapter for the Test Explorer' requires a version of the .NET Framework that is not installed." when .Net 4.5.1 was installed. Change allows 4.5 or greater to be present.
> Resolve dependency issue when .Net 4.5.1 or > is present

- Chutzpah/JSRunners/chutzpahRunner.js
passed parameter should be a string which is eval-ed in the phantomJS host's context.
> Adding ability to call phantomJS host through window.callPhantom

- Chutzpah/Chutzpah.csproj
- Chutzpah/IProcessHelper.cs
- Chutzpah/ProcessHelper.cs
- Chutzpah/TestOptions.cs
- Chutzpah/TestRunner.cs
- Chutzpah/Utility/BrowserPathHelper.cs
- ConsoleRunner/CommandLine.cs
- ConsoleRunner/Program.cs
Enhance openInbrowser parameter to accept an optional browseranme
value. such as ie, chrome and firefox. Chutzpah will try to open the
test page in the psecified browser. If browser name is not provided,
Chutzpah will try to open the test page using the default browser. If no
default browser is found, Chutzpah will open the test page using the
default app for html file
> openInBrowser enhancement

- Chutzpah/TestFiles/Jasmine/v1/jasmine.html
- Chutzpah/TestFiles/Jasmine/v2/jasmine.html
- Chutzpah/TestFiles/Mocha/mocha.html
- Chutzpah/TestFiles/QUnit/qunit.html
I've added [Mark of the Web](https://msdn.microsoft.com/en-us/library/ms537628.aspx) to harness files to make IE think that file is serve from Internet instead of file system with for some reasons have more restrictions. Please follow the link for details.
I find no way to unit test this, but I have tested it locally and it works for me.
Hope you find this fix useful.
> Adding Mark of the Web to prevent scripts blocking in Internet Explorer

- Chutzpah/Coverage/BlanketJsCoverageEngine.cs
I believe the chutzpah.json config file uses the References to include files that are local that should be loaded for testing. The fellow that setup our TypeScript tests also included http:// references to files that were needed (mostly angular related). I found that this broke when used with the /codecoverage option because it tries to determine the LocalPath of the URI. This change makes sure that only file based URIs are checked for their LocalPath.
> Blanket Coverage: Only proceed to map to local path when URI scheme is file

- Chutzpah/Constants.cs
- Chutzpah/FileProbe.cs
- Chutzpah/TestHarness.cs
Adding *.cshtml to the list of file extensions that is allowed to be embedded in the test via the <template/> tag.
> Fixes #373

- Chutzpah/Chutzpah.csproj
- Chutzpah/ITestLauncher.cs
- Chutzpah/Models/TestLaunchMode.cs
- Chutzpah/TestOptions.cs
- Chutzpah/TestRunner.cs
- Chutzpah/Utility/ComHelpers.cs
- Chutzpah/Utility/ProcessExtensions.cs
- ConsoleRunner/Program.cs
- Facts/Library/TestRunnerFacts.cs
- VS.Common/DteHelpers.cs
- VS.Common/VS.Common.csproj
- VS.Common/VsDebuggerTestLauncher.cs
- VS2012.TestAdapter/ChutzpahTestExecutor.cs
- VisualStudioContextMenu/VisualStudioContextMenuPackage.cs
Revised implementation as previously discussed (#381).
Now developed in VS2013. The problem with VS.Common was something to do with the way I was copying DLLs directly into the TestWindow\Extensions folder, I think.
Another odd thing was that if I DON'T bump the version number but keep the current number (4.0.3), installing the newly built VSIX package results in the previous, originally-installed package being re-installed. Furthermore, when building with the original version number, it seems to want to re-install the newly built package, right there during the build process. Finally, if the VS process doesn't have admin rights that attempt eventually bombs out after a couple of minutes.
It seems that the build.bat should be run as ```build package 4.0.4``` or whatever version number is …
> VS Debugger Support (2nd attempt)

- Chutzpah/Transformers/SummaryTransformer.cs
- Facts/Facts.csproj
- Facts/Library/Transformers/SummaryTransformerFacts.cs
Fixes #411. The BOM causes errors when read by many Java libraries, including those used by Jenkins. It's optional, so it can simply be removed, making (in particular) Jenkins integration easier.
> Remove BOM from transformed result output

- Chutzpah/Transformers/JUnitXmlTransformer.cs
- Chutzpah/Transformers/SummaryTransformer.cs
- Facts/Library/Transformers/JUnitXmlTransformerFacts.cs
Fixes #409. The timings in the JUnit XML format are required to be in
seconds, not milliseconds.
> Use seconds for timings in JUnit XML

- Chutzpah/Coverage/BlanketJsCoverageEngine.cs
- Chutzpah/Coverage/ICoverageEngine.cs
- Chutzpah/CoverageOptions.cs
- Chutzpah/Models/ChutzpahTestSettingsFile.cs
- Chutzpah/TestContextBuilder.cs
- ConsoleRunner/CommandLine.cs
- ConsoleRunner/Program.cs
- Facts.Integration/Coverage.cs
- Facts/ConsoleRunner/CommandLineFacts.cs
- Facts/Library/Models/ChutzpahTestSettingsServiceFacts.cs
My implementation of a solution for #404. Adds a /coverageIgnore command-line option (and corresponding "CodeCoverageIgnores" option in chutzpah.json), much like the existing /coverageInclude and /coverageExclude options. Ignored files are not added to the CoverageData object, thus don't appear in the coverage output.
> adds /coverageIgnore option to exclude files from code coverage results

- Chutzpah/Coverage/BlanketJsCoverageEngine.cs
- Chutzpah/Models/CoverageData.cs
- Facts.Integration/CoverageFileDataFacts.cs
- Facts.Integration/Facts.Integration.csproj
- Facts/Library/Coverage/BlanketJsCoverageEngineFacts.cs
Fix bugs: 
1) AMD modules and different "non canonical" references
2) CoverageData.Merge do not update Percentage
And add tests
> Fix bugs: AMD modules and different "non canonical" references and CoverageData.Merge do not update Percentage

- Chutzpah/Chutzpah.csproj
- Chutzpah/Transformers/EmmaXmlTransformer.cs
- Chutzpah/Transformers/SummaryTransformerProvider.cs
- Facts/Facts.csproj
- Facts/Library/Transformers/EmmaXmlTransformerFacts.cs
This PR attempts to solve issue #403 by using the Emma XML format (schema example [here](http://emma.sourceforge.net/coverage_sample_c/coverage.xml)).
The new transformer has 100% coverage.
I tested this in a local installation of Jenkins (version 1.646, Emma version 1.29) for a project of mine and got the following output:
The fact that the results are placed in the "method" column seems to be an issue with Emma. The numeric values actually correspond to the "line" column.
I don't think Chutzpah distinguishes between packages, classes and files; therefore, I'm not considering per-package or per-class coverage, only per-file coverage. Let me know whether you'd like me to consider a folder a "package".
> Added Emma XML coverage transformer + Unit tests

- Chutzpah/ReferenceProcessor.cs
- Facts/Library/ReferenceProcessorFacts.cs
Given that path contains a substring identical to the file extension,
AmdPath was incorrect.
This commit will make sure only the file extension is removed when
setting AmdFilePath.
> Fix AmdFilePath when path contains file extension

- Chutzpah/Chutzpah.csproj
- Chutzpah/ChutzpahTestSettingsService.cs
- Chutzpah/Models/ChutzpahTestSettingsFile.cs
- Chutzpah/TestOptions.cs
- Chutzpah/TestRunner.cs
- Chutzpah/Utility/ValidationHelper.cs
- ConsoleRunner/CommandLine.cs
- ConsoleRunner/Program.cs
- Facts/ConsoleRunner/CommandLineFacts.cs
- Samples/Basic/Jasmine/chutzpah.json
Add support of proxy setting to headless browser in test runner. The
"Proxy" can be passed in either console runner or json setting file in
the format of [address/host]:[port]. If not provided, it will fall back
to default none proxy setting.
> Add support of proxy setting

- Chutzpah/TestHarness.cs
I have multiple templates that I pull in from html files. Giving them all the same ID doesn't help, so my only option is to hard-code all 20 of my references and update them every time a developer renames or makes a new one.
If you take this simple change, I can then use an initialization js script to format the ID the way I want (lower case and replace / with -, but that's on me).
TLDR: same hard-coded ID is slightly limited.
> use the file name as the script tag ID

- Chutzpah/FileProbe.cs
Issue:
We have one project which has amdPath added for each JS files ( including test files). When I tried running tests using chutzpah on the project. I found that some portion of amdPath generated by chutzpah for the test files is still coming in lower case.
While I can see that as part of commit “5145879: fix path casing” done on 12 Nov 2017, @mmanela fixed most of the casing issue in the test file path generation. but we are still hitting into the test file path casing issue.
Fix
=====
Passing  lowerCase flag = false to NormalizeFilePath in the method FindScriptFiles()
> #672: Fix for the Chutzpah doesn't discover JS tests in which AmdPaths with Pascal case for the test modules are added

- Chutzpah/Coverage/CoverageOutputGenerator.cs
The code in the coverage html generated by Chutzpah shows as if it has no indentation in the browser. This change will make the browser preserve the whitespaces.
> Maintain whitespaces of the code in the generated coverage report

- Chutzpah/ChutzpahJSRunners/Chrome/chutzpahRunner.js
- Chutzpah/ExecutionProviders/NodeTestExecutionProvider.cs
When the engine is set to jsdom, tests fail to start when chutzpah.console.exe is in a path that contains spaces. It looks like the runner path argument isn't being escaped in NodeTestExecutionProvider.
> Escape spaces for runner path in NodeTestExecutionProvider.

- Chutzpah/ChutzpahJSRunners/JsDom/chutzpahRunner.js
- Chutzpah/ExecutionProviders/NodeTestExecutionProvider.cs
- Chutzpah/Models/ChutzpahTestSettingsFile.cs
A corresponding update should be made to the wiki to document the new option EngineOptions.NodeInspect.
When NodeInspect is true, the first argument to the node.exe process will be `--inspect-brk`, which allows a remote debugger to connect to localhost:9229. Furthermore, the debugger will break at the first line of execution, meaning the test will not proceed until the user has opened the debugger and continued the script.
The easiest way to do this is open Chrome and go to about:inspect. Once the node.exe process is started, there will be a Remote Target listed, similar to this:
Just click Inspect to open the debugger.
Maybe: disable the TestFileTimeout when this option is used?
> Add option to inspect node process.

- readme.md
Updated readme with a link to the Visual Studio Code Chutzpah extension.
> Add link to VSCode Chutzpah extension

- default.ps1
- nuget.config
After I pulled the repository for the first time. I had issues to build it.
- Your machine nuget source get in a way 
Fixed by introducing nuget.config that points to nuget.org only to search for packages primarily there
- The environment variable Chutzpah_MSBuild_Path was never used in the build
> Imporve build

- Chutzpah/Node/packages/package-lock.json
- Chutzpah/Node/packages/package.json
Version of jsdom depends transitively on lodash 4.17.11 which has security vulnerabilities.  The latest version of jsdom no longer has this problem.
> Updating version of lodash to 14.17.15

- Chutzpah/ChutzpahJSRunners/Chrome/chutzpahRunner.js
Disable CORS by default in Chrome runner to enable running tests in Headless Chrome which utilize AJAX requests. This is consistent to the behavior when running tests with PhantomJS as target engine.
> Disable CORS by default

- Chutzpah/ChutzpahJSRunners/Chrome/chutzpahRunner.js
The browser variable is declared in the inner scope of a try-catch block.
There are [references](https://github.com/mmanela/chutzpah/blob/6fb2df4ec43000dfcf51808c71383e11b0cec585/Chutzpah/ChutzpahJSRunners/Chrome/chutzpahRunner.js#L342) to this variable outside that block which may lead to a 'variable not defined'.
This leads to an issue when the execution of a test file exceeds the configured timeout. In this case the chutpah.console.exe will terminate with a generic 'exit code 2' from the [general error handler in the qunitRunner.js component](https://github.com/mmanela/chutzpah/blob/6fb2df4ec43000dfcf51808c71383e11b0cec585/Chutzpah/ChutzpahJSRunners/Chrome/qunitRunner.js#L21) instead of the intended timeout error.
> Move 'browser' variable to outer scope

- Chutzpah/Constants.cs
- Chutzpah/FileProbe.cs
- Chutzpah/ITestLauncher.cs
- Chutzpah/Models/ChutzpahTestSettingsFile.cs
- Chutzpah/TestRunner.cs
- Chutzpah/UrlBuilder.cs
- VS.Common/Settings/ChutzpahUTESettings.cs
- VS.Common/VS.Common.csproj
- VS.Common/VsDebuggerTestLauncher.cs
- VS.Common/app.config
- VS.Common/packages.config
- VS2012.TestAdapter/VS2012.TestAdapter.csproj
- VS2012.TestAdapter/app.config
- VS2012.TestAdapter/packages.config
- VS2012/VS2012.csproj
- VS2012/app.config
- VS2012/packages.config
- VisualStudioContextMenu/ChutzpahSettings.cs
- VisualStudioContextMenu/VisualStudioContextMenu.csproj
- VisualStudioContextMenu/app.config
- VisualStudioContextMenu/packages.config
Added IEBrowserTabOpenTimeout setting
Fixed typos
Waiting until Internet Explorer process being debugged has exited before continuing when using the web server
Using Microsoft.VisualStudio.Shell.14 nuget package
Using Microsoft.VSSDK.BuildTools.15.0.26201 released nuget package
Fixes #787
> Waiting until Internet Explorer process being debugged has exited before continuing when using the web server
